const data = {
  SET_USER_ACTION: 'SET_USER_ACTION',
  SET_USER_ACTION_REGISTER: 'SET_USER_ACTION_REGISTER',
  SET_USER_ACTION_ADMIN_MANAGER: 'SET_USER_ACTION_ADMIN_MANAGER',

};
export default data;
